FROM alpine:3.10

RUN set -ex \
    && echo "https://mirrors.aliyun.com/alpine/v3.10/main" > /etc/apk/repositories \
    && echo "https://mirrors.aliyun.com/alpine/v3.10/community" >> /etc/apk/repositories \
    && echo "https://mirrors.aliyun.com/alpine/edge/main" >> /etc/apk/repositories \
    && echo "https://mirrors.aliyun.com/alpine/edge/testing" >> /etc/apk/repositories \
    && apk update \
    && apk upgrade \
    && apk add --no-cache \
           tzdata 

# Timezone
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone
